# Generated by Django 3.1.4 on 2021-03-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210328_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='network.posts'),
        ),
    ]
