# Generated by Django 3.1.4 on 2021-02-28 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='Bidder',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='watchBidder',
        ),
        migrations.AddField(
            model_name='bid',
            name='watchBidder',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_watchBidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
