# Generated by Django 3.1.4 on 2021-02-28 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210228_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_identifier',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
