# Generated by Django 3.1.4 on 2021-02-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210228_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='desctiption',
        ),
    ]
