# Generated by Django 3.1.4 on 2021-02-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_desctiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='display_button',
            field=models.BooleanField(default=True),
        ),
    ]
