# Generated by Django 3.1.4 on 2021-03-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_display_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listing_comment', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
