# Generated by Django 3.1.4 on 2021-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210301_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
