# Generated by Django 3.1.4 on 2021-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210302_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
