# Generated by Django 3.1.4 on 2021-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=64)),
                ('zone', models.IntegerField()),
                ('road', models.IntegerField()),
                ('building', models.IntegerField()),
                ('postal', models.CharField(max_length=64)),
                ('phoneNumber', models.IntegerField()),
                ('emailSupplier', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('nameP', models.CharField(max_length=64)),
                ('brand', models.IntegerField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
                ('supplierP', models.ForeignKey(on_delete=models.SET('Company Deleted'), related_name='supplierP', to='rfq.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pNumber', models.IntegerField()),
                ('email', models.CharField(max_length=64)),
                ('position', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=models.SET('Company Deleted'), related_name='supplierC', to='rfq.supplier')),
            ],
        ),
    ]
