# Generated by Django 3.1.4 on 2021-03-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone1', models.CharField(max_length=64)),
                ('road1', models.CharField(max_length=64)),
                ('building1', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadName', models.CharField(max_length=64)),
                ('roadLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zlocation', to='rfq.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=64)),
                ('blocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingZone', to='rfq.zone')),
                ('broad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingRoad', to='rfq.road')),
            ],
        ),
    ]
