# Generated by Django 3.1.4 on 2021-04-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0004_auto_20210401_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceP', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrice', to='rfq.product')),
                ('supplierPp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierPp', to='rfq.supplier')),
            ],
        ),
    ]
