# Generated by Django 3.1.4 on 2021-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=64)),
                ('county', models.IntegerField()),
                ('postal', models.CharField(max_length=64)),
                ('clientNumber', models.IntegerField()),
                ('emailClient', models.CharField(max_length=64)),
            ],
        ),
    ]
