# Generated by Django 3.1.4 on 2022-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
