# Generated by Django 4.0.2 on 2022-04-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_client_remove_supplier_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('product', models.ManyToManyField(related_name='jobProduct', to='company.Product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.job'),
            preserve_default=False,
        ),
    ]
