# Generated by Django 4.0.2 on 2022-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_client_job_job_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='client',
        ),
    ]
