# Generated by Django 4.0.2 on 2022-04-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_job_job_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='jobProduct', to='company.Product'),
        ),
    ]
