# Generated by Django 3.1.4 on 2022-01-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0006_auto_20220126_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameC', models.CharField(max_length=64)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=64)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='Personel',
        ),
    ]
