# Generated by Django 4.0.2 on 2022-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_job_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='product',
        ),
        migrations.AddField(
            model_name='job',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='jobProducts', to='company.Product'),
        ),
    ]
