# Generated by Django 3.1.4 on 2022-01-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0007_auto_20220126_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
