# Generated by Django 4.0.2 on 2022-04-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_job_product_job_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='products',
            new_name='product',
        ),
    ]
