# Generated by Django 3.1.4 on 2022-02-17 16:54

from django.db import migrations, models
import django.db.models.deletion
import polymorphic.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0009_auto_20220127_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='nameS',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(verbose_name=polymorphic.models.PolymorphicModel),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameS', models.CharField(max_length=64)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_company.company_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.company'),
            preserve_default=False,
        ),
    ]
