# Generated by Django 4.0.2 on 2022-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_products_job_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='RFQ', max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='value',
            field=models.IntegerField(blank=True),
        ),
    ]
