# Generated by Django 4.0.2 on 2022-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_job_status_alter_job_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
