# Generated by Django 3.1.4 on 2022-02-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0010_auto_20220217_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_company.product_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.product')),
                ('priceP', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.supplier')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('company.product',),
        ),
    ]
