# Generated by Django 3.1.4 on 2022-02-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20220217_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.supplier'),
        ),
    ]
