# Generated by Django 3.1.4 on 2022-02-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20220217_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='priceP',
            new_name='productPrice',
        ),
    ]
