# Generated by Django 4.0.2 on 2022-04-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_jobitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='product',
        ),
    ]
