# Generated by Django 3.1.4 on 2022-02-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0013_auto_20220217_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='PriceP',
        ),
        migrations.RenameField(
            model_name='pricep',
            old_name='productPrice',
            new_name='price',
        ),
    ]
