# Generated by Django 4.0.2 on 2022-05-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_job_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobItem',
            new_name='Supply',
        ),
    ]
