# Generated by Django 3.1.4 on 2022-02-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0014_auto_20220217_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceP',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='productPrice',
        ),
    ]
