# Generated by Django 4.0.2 on 2022-05-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_rename_jobitem_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='maxBuying',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worstBuying', to='company.price'),
        ),
        migrations.AddField(
            model_name='supply',
            name='minBuying',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestBuying', to='company.price'),
        ),
    ]
