# Generated by Django 3.1.4 on 2022-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20220217_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='supplier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
