# Generated by Django 4.0.6 on 2022-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_supply_maxbuying_supply_minbuying'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deliveryNo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='invoiceNo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='receiptNo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
