# Generated by Django 4.0.6 on 2022-08-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_job_deliveryno_job_invoiceno_job_receiptno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='deliveryNo',
            new_name='LPONo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='invoiceNo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='receiptNo',
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deliveryNo', models.CharField(blank=True, max_length=64)),
                ('invoiceNo', models.CharField(blank=True, max_length=64)),
                ('receiptNo', models.CharField(blank=True, max_length=64)),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedJob', to='company.job')),
            ],
        ),
    ]
